# Generated by Django 3.2.7 on 2021-09-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(help_text='name of the owner of the car', max_length=200, verbose_name='name')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carlisting.carmake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carlisting.carmodel')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carlisting.cartype')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carlisting.car')),
            ],
        ),
    ]
